Add support for sending mails through SES
ChluNetwork/chlu-api-publish pull request #4
Opened 2018-08-20 13:53 UTC by kulpreet

Assumes that the Mailer#send_mail will be called from a background
worker task

2018-08-20 15:09 UTC, fazo96 requested changes
All good except I think it'd be best to pass the smtp parameters to the constructor instead of reading them from the ENV directly. The reading from the ENV will happen at a higher level (CLI arg parsing for example)

We can also keep it like it is now, I don't think the use of ENV variables like this will be a problem, it just does not feel very clean

What do you think @kulpreet?

2018-08-20 15:09 UTC, fazo96 commented on src/mailer.js
> +    if (isEmpty(process.env.SMTP_USER)) {
typo here

2018-08-20 15:09 UTC, fazo96 commented on src/mailer.js
> +    console.log(mailOptions)
I think we should pass a logger for these so chatter can be turned off in tests, like we do in other projects

2018-08-20 15:26 UTC, kulpreet commented
Agree totally with what you are saying. But the ChluIpfs constructor is so embedded in, it is difficult to disentangle options parsing for other modules, that is why I just hacked it as process.env for now :)

2018-08-21 07:38 UTC, fazo96 approved these changes

2018-08-21 07:38 UTC, merged